package tictactoegame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Random;
import javax.swing.JLabel;
import jdk.jfr.FlightRecorder;

/**
 *
 * @author PC
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    SettingsPage settingsPage;
    SinglePlayerPage singlePlayerPage;
    MultiPlayerPage multiPlayerPage;
    GamePage gamePage;
    StartPage startPage;
    CardLayout cardLayout;
    Container container;
    Player xPlayer;
    Player oPlayer;
    FontSizes fontSize = FontSizes.MEDUIM;
    boolean isTwoPlayerGame;
    public Main() {       
        initComponents();
        creatContainer();
        creatAndShowStartPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe Game");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    private void creatContainer() {
        startPage = new StartPage();
        singlePlayerPage = new SinglePlayerPage();
        multiPlayerPage = new MultiPlayerPage();
        settingsPage = new SettingsPage();
        cardLayout = new CardLayout();
        container = this.getContentPane();
        
        container.setLayout(cardLayout);
        container.getLayout().addLayoutComponent("startPage", startPage);
        container.add(startPage);       

        container.getLayout().addLayoutComponent("singlePlayerPage", singlePlayerPage);
        container.add(singlePlayerPage);
     
        container.getLayout().addLayoutComponent("multiPlayerPage", multiPlayerPage);
        container.add(multiPlayerPage);
               
        container.getLayout().addLayoutComponent("settingsPage", settingsPage);
        container.add(settingsPage);
        
      
    }
    private void creatAndShowStartPage() {
        startPage.SinglePlayerBtn.addActionListener(singlePlayerBtnListener);
        startPage.multiPlayerBtn.addActionListener(multiPlayerBtnListener);
        startPage.settingsBtn.addActionListener(settingsBtnListener);
        
        cardLayout.show(container, "startPage");
    }

    private void creatAndShowSinglePlayerPage() {
        singlePlayerPage.setFontSize(fontSize);
        singlePlayerPage.singlePlayerStartBtn.addActionListener(singlePlayerStartBtnListener);
        singlePlayerPage.singlePlayerBackBtn.addActionListener(singlePlayerBackBtnListener);
        
        cardLayout.show(container, "singlePlayerPage");
    }

    private void creatAndShowMultiPlayerPage() {
        multiPlayerPage.setFontSize(fontSize);
        multiPlayerPage.multiPlayerBackBtn.addActionListener(multiPlayerBackBtnListener);
        multiPlayerPage.multiPlayerStartBtn.addActionListener(multiPlayerStartBtnListener);

        cardLayout.show(container, "multiPlayerPage");
    }

    private void creatAndShowSettingsPage() {
        settingsPage.settingsBackBtn.addActionListener(settingsBackBtnListener);
        settingsPage.fontSizeComboBox.addItemListener(fontSizeItemListener);

        cardLayout.show(container, "settingsPage");
    }

    private void creatAndShowGamePage() {
        gamePage = new GamePage();
        xPlayer = new Player(0, multiPlayerPage.playerXField.getText(), true, 'X');
        oPlayer = new Player(0, multiPlayerPage.playerOField.getText(), false, 'O');
        
        gamePage.gamePageBackBtn.addActionListener(gamePageBackBtnListener);
        gamePage.restartGameBtn.addActionListener(restartgameBtnListener);
        gamePage.addBoardLabels();
        gamePage.setFontSize(fontSize);
        setBoardLabelsListener();
        gamePage.xPlayerNameLabel.setText(xPlayer.getName());
        if (isTwoPlayerGame) {
            gamePage.oPlayerNameLabel.setText(oPlayer.getName());
        }
        
        container.getLayout().addLayoutComponent("gamePage", gamePage);
        container.add(gamePage); 
        cardLayout.show(container, "gamePage");
    }

    private void setBoardLabelsListener() {
        gamePage.boardLabels[0].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[1].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[2].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[3].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[4].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[5].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[6].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[7].addMouseListener(boardLabelsListener);
        gamePage.boardLabels[8].addMouseListener(boardLabelsListener);
    }
    
    private void removeBoardLabelsListener() {
        gamePage.boardLabels[0].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[1].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[2].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[3].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[4].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[5].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[6].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[7].removeMouseListener(boardLabelsListener);
        gamePage.boardLabels[8].removeMouseListener(boardLabelsListener);
    }
//start page listener
    ActionListener singlePlayerBtnListener = (evt) -> {
        creatAndShowSinglePlayerPage();
    };

    ActionListener multiPlayerBtnListener = (evt) -> {
        creatAndShowMultiPlayerPage();
    };

    ActionListener settingsBtnListener = (evt) -> {
        creatAndShowSettingsPage();
    };
    //single page listener
    ActionListener singlePlayerStartBtnListener = (evt) -> {
        xPlayer = new Player(0, singlePlayerPage.playerNameField.getText(), true, 'X');
        isTwoPlayerGame = false;
        creatAndShowGamePage();
    };

    ActionListener singlePlayerBackBtnListener = (evt) -> {
        cardLayout.show(container, "startPage");
    };

    //multi page listener
    ActionListener multiPlayerStartBtnListener = (evt) -> {
        isTwoPlayerGame = true;
        creatAndShowGamePage();
    };

    ActionListener multiPlayerBackBtnListener = (evt) -> {
        cardLayout.show(container, "startPage");
    };
    //settings page listener
    ItemListener fontSizeItemListener = (e) -> {

        if (e.getItem().equals(settingsPage.fontSizeComboBox.getItemAt(0))) {
            fontSize = FontSizes.SMALL;
        } else if (e.getItem().equals(settingsPage.fontSizeComboBox.getItemAt(1))) {
            fontSize = FontSizes.MEDUIM;
        } else {
            fontSize = FontSizes.LARGE;
        }
        startPage.setFontSize(fontSize);
        settingsPage.setFontSize(fontSize);
    };

    ActionListener settingsBackBtnListener = (evt) -> {
        cardLayout.show(container, "startPage");
    };
    //game page listener
    ActionListener gamePageBackBtnListener = (evt) -> {
        //remove game page
        gamePage = null;
        if (isTwoPlayerGame) {
            cardLayout.show(container, "multiPlayerPage");
        } else {
            cardLayout.show(container, "singlePlayerPage");
        }
    };
    
    ActionListener restartgameBtnListener = (evt) -> {
        gamePage = null;
        creatAndShowGamePage();
    };
    
    MouseListener boardLabelsListener = new MouseListener() {
        @Override
        public void mouseClicked(MouseEvent e) {
        }

        @Override
        public void mousePressed(MouseEvent e) {
            if (((JLabel) e.getSource()).getText().equals("") && gamePage.getNumberOfClick() < 9) {
                if (xPlayer.isPlayerTurn()) {                  
                    ((JLabel) e.getSource()).setForeground(xPlayer.getColorIcon());
                    ((JLabel) e.getSource()).setText("" + xPlayer.getPlayerIcon());
                    xPlayer.setPlayerTurn(false);
                    gamePage.plusNumberOfClick();
                    gamePage.checkIfThereIsAWinner();
                    if(!gamePage.isGameEnd()) {
                        gamePage.xPlayerNameLabel.setForeground(Color.BLACK);
                        gamePage.oPlayerNameLabel.setForeground(Color.red);
                    } else {
                        System.out.println("rm");
                        removeBoardLabelsListener();                       
                    }
                } else if (isTwoPlayerGame && gamePage.getNumberOfClick() < 9) {
                    ((JLabel) e.getSource()).setText("" + oPlayer.getPlayerIcon());
                    ((JLabel) e.getSource()).setForeground(oPlayer.getColorIcon());
                    xPlayer.setPlayerTurn(true);
                    gamePage.plusNumberOfClick();
                    gamePage.checkIfThereIsAWinner();
                    if(!gamePage.isGameEnd()) {
                        gamePage.oPlayerNameLabel.setForeground(Color.BLACK);
                        gamePage.xPlayerNameLabel.setForeground(Color.blue);
                    } else {
                        removeBoardLabelsListener();
                    }
                } 
                if(!isTwoPlayerGame && !xPlayer.isPlayerTurn() && gamePage.getNumberOfClick() < 9 && !gamePage.isGameEnd()) {
                    int randomBoardLabel = new Random().nextInt(9);
                    while (true) {
                        if (gamePage.boardLabels[randomBoardLabel].getText().equals("")) {
                            gamePage.boardLabels[randomBoardLabel].setText("O");
                            gamePage.boardLabels[randomBoardLabel].setForeground(Color.red);
                             if(!gamePage.isGameEnd()) {
                                gamePage.oPlayerNameLabel.setForeground(Color.BLACK);
                                gamePage.xPlayerNameLabel.setForeground(Color.blue);
                                xPlayer.setPlayerTurn(true);
                            } else {
                                 removeBoardLabelsListener();
                             }
                            break;
                        } else {
                            randomBoardLabel = new Random().nextInt(9);
                        }

                    }
                }
            }
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }

    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
